[bans]
multiple-versions = "deny"
deny = []
skip = []

[advisories]
ignore = [
    # Unmtaintained `safemem` dependency - only used by plist to build
    "RUSTSEC-2023-0081",
]

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
]
