on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: CI
jobs:
  lint:
    name: Lint
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy, rustfmt"
      - uses: Swatinem/rust-cache@v2
      # make sure all code has been formatted with rustfmt
      - run: cargo fmt --all -- --check --color always
      # run clippy to verify we have no warnings
      - run: cargo fetch --target x86_64-apple-darwin
      - run: cargo clippy --features pre-built -- -D warnings

  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: EmbarkStudios/cargo-deny-action@v1

  test-source:
    name: Test (source build)
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fetch --target x86_64-apple-darwin
      - run: cargo build

  test:
    name: Test (pre-built)
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fetch --target x86_64-apple-darwin
      - run: cargo build --verbose --features pre-built
