on: [push, pull_request]
name: CI
jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # make sure all code has been formatted with rustfmt
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --color always

      # run clippy to verify we have no warnings
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1

  test:
    name: Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
